id: PA2CB44EA
initial_creation_type: input
source_metadata:
  title: Nyingma Mönlam Series
  language: bo
  description: 'The following texts are recited during the annual Nyingma Mönlam prayer
    festival in Bodhgaya:'
  volume:
    8e5c3ba04f4a4713914ca712ac06d19a:
      title: Verses of the Eight Noble Auspicious Ones
      parent: Eight Auspicious Ones
    c4cf44fc3e5d4dd9978b89050b6843d3:
      title: The Ritual of the Bodhisattva Vow According to the Tradition of Patrul
        Rinpoche
      parent: Bodhisattva Vow
    c879017f7a394a4aba25873c7cacb57f:
      title: The Bodhisattva’s Confession of Downfalls (Nyingma Version)
      parent: Confession
    9e653b23cf8e4a4bbff9f04e687480b4:
      title: 'Accomplishing the Lama through the Seven-Line Prayer: A Special Teaching
        from the Lama Sangdü'
      parent: Seven-Line Prayer
    43ed02d038af4648ab9d2807d4a3adee:
      title: 'The Garland of Utpala Flowers: A Prayer to the Masters of the Lineage
        of Zabtik Drolchok'
      parent: Zabtik Drolchok
    23b087e60bf54305b1e907e000cc1d70:
      title: 'The Treasury of Blessings: A Practice of Buddha Śākyamuni'
      parent: Śākyamuni Practice
    5327686653e645eeb5085e718e2534a0:
      title: A Brief Practice for Paying Homage and Making Offerings to the Buddha
        together with his retinue of Arhats
      parent: Sixteen Arhats
    ebfbf95a77ec4bf0996f07d05d25e7cb:
      title: The General Visualization for Prayers to Guru Rinpoche
      parent: Guru Rinpoche Visualization
    682ac629bc33481a8087895196a3ad9f:
      title: 'Le''u Dünma—Chapter 1: The Prayer to the Three Kāya Guru'
      parent: Le'u Dünma
    028e441348ef48cb9857ea1de3d8ca0e:
      title: 'Le''u Dünma—Chapter 2: The Prayer Requested by King Tri Songdetsen'
      parent: Le'u Dünma
    1ee0493d7d1d4803ba557d88a95c6e22:
      title: 'Le''u Dünma—Chapter 3: The Prayer Requested by Khandro Yeshe Tsogyal'
      parent: Le'u Dünma
    b977a96de9704a20b3dcaf8e198637c1:
      title: 'Le''u Dünma—Chapter 4: The Prayer Requested by Namkhe Nyingpo'
      parent: Le'u Dünma
    50a0c91f86a84407939e68d31473ef3a:
      title: 'Le''u Dünma—Chapter 5: The Prayer Requested by Nanam Dorje Dudjom'
      parent: Le'u Dünma
    64c20b391a95472daa61c728bd4f69b9:
      title: 'Le''u Dünma—Chapter 6: The Prayer Requested by Prince Mutri Tsenpo'
      parent: Le'u Dünma
    dbf0d17b40ec456caa62f4e3bb373af0:
      title: Le'u Dünma—Chapter 7. The Prayer to Guru Rinpoche that Spontaneously
        Fulfills All Wishes (Sampa Lhundrupma)
      parent: Le'u Dünma
    247c3c0c37b84fccbcb88bdc35facd92:
      title: The Prayer Which Removes All Obstacles from the Path (Barché Lamsel)
      parent: Barché Lamsel
    b98edbd78ef44123b0707d60f41f2cee:
      title: The Prayer in Six Vajra Lines
      parent: Guru Rinpoche Prayers
    0a0f27eb850f4649a8692da0fbfb2bd0:
      title: The Prayer that Swiftly Fulfils All Wishes (Sampa Nyur Drupma)
      parent: Guru Rinpoche Prayers
    7b254ffdb1ff481aa3eeb4308f78d1dd:
      title: 'Wisdom''s Bestowal: A Way to Accumulate the Recitation of the Tantra
        ''Chanting the Names of Mañjuśrī'' (Mañjuśrī Nāma Saṃgīti)'
      parent: Chanting the Names of Mañjuśrī
    660dca6bb5034eeb818aad769f2b7dd0:
      title: Ārya Mañjuśrī Tantra Garbha
      parent: Mañjuśrī
    eef2cbc0fd204216bc416d034037026a:
      title: The Praise to Mañjuśrī—Glorious Wisdom's Excellent Qualities
      parent: Mañjuśrī
    0660d8ba61444bc780702b405295b6df:
      title: The Heart of the Transcendent Perfection of Wisdom
      parent: Heart Sūtra
    c616a5e9eb0e42b1bea4dfae41a74e92:
      title: The Means for Accomplishment called the Blazing Wheel
      parent: Blazing Wheel
    033091b79ed244c286e68aa1c811b1a9:
      title: 'The Blazing Tower: A Daily Practice of Uṣṇīṣa-Sitātapatrā'
      parent: Sitātapatrā
    c59a6f5750fb406bbb904b71127a89e0:
      title: A Daily 'Hand-Clapping' Practice of Siṃhamukhā
      parent: Siṃhamukhā
    9e6d73c38b9b47c69c291d314033532e:
      title: The Dhāraṇī of Amitāyus
      parent: Dhāraṇī of Amitāyus
    cec5910ab0674ff496b075fed3d7143b:
      title: 'The King of Aspiration Prayers: Samantabhadra''s “Aspiration to Good
        Actions” (Zangchö Mönlam)'
      parent: Zangchö Mönlam
    a8dace62478448a69c240e9f3c5d1d84:
      title: Maitreya's Aspiration
      parent: Maitreya's Aspiration
    f4ccd108fb35408a84d69387f1834b73:
      title: Aspiration to Generate Bodhicitta, Utterly Pure and Supreme
      parent: Aspiration to Generate Bodhicitta
    6ab331426df742b5b2da333350a9e958:
      title: The Powerful Prayer of Aspiration from the Tantra of the Great Perfection
        that Reveals the All-Penetrating Wisdom Mind of Samantabhadra (Kunzang Mönlam)
      parent: Kunzang Mönlam
    6b462b162547465aa0b6087721463ff1:
      title: Brief Sukhāvatī Aspiration
      parent: Amitābha Mönlam
    665b4826357a43948eb1420106fc27a5:
      title: Dedication from Vajravārāhī Cycle of Namchö revealed by Mingyur Dorje
      parent: Amitābha Mönlam
    77b86b5767ef4b2fa856223d61e6cf53:
      title: The Aspiration of the Vajradhātu Maṇḍala
      parent: Aspiration of Vajradhātu Maṇḍala
    92af134e45d64ad3854a0ac7dedb60ea:
      title: Yeshe Tsogyal's Prayer
      parent: Yeshe Tsogyal’s Prayer
    31c9301075224da9a6c8c99d0b95b99e:
      title: Prayer for Dispelling Famine
      parent: Thangtong Gyalpo Prayers
    3ed5b85e6fa242bd8bacedcc9b2d443c:
      title: 'The Verses that Saved Sakya from Sickness: A Prayer for Pacifying the
        Fear of Disease'
      parent: Thangtong Gyalpo Prayers
    654511163f504f6b99ea02c3e2b18b53:
      title: 'The Sage''s Powerful Words of Truth: A Prayer for the Spread of the
        Omniscient Buddha''s Teachings'
      parent: Sage's Powerful Words of Truth
    9f21490d82f94cadb0bc05f506f5a16f:
      title: 'The Rishi''s Maledictory Incantation: An Invocation of Wisdom Mind and
        Sacred Pledges for Reversing the Disturbances and Agitations of Dark Times
        In the Form of an Aspiration Prayer'
      parent: Rishi's Maledictory Incantation
    24ac328c08f146f6bcab6b439ccda4df:
      title: 'The Adamantine Magical Wheel: Invoking the Profound Pledge of Padmākara,
        the Glorious Victor, to Avert the Final War'
      parent: Adamantine Magical Wheel
    6f7f45f3d5ed4cfa8e44d67a62330dfa:
      title: 'The Resounding Drum of Truth: A Prayer and Aspiration'
      parent: Resounding Drum of Truth
    121423793a4546c9a2c701d63dd3a513:
      title: The Prayer of the Words of Truth
      parent: Words of Truth
    8a82e1d421c84b09afb3648c8c9a8cf3:
      title: The Prayer of the Ground, Path & Fruition – From the Heart-Essence of
        the Vast Expanse
      parent: Ground, Path & Fruition Prayer
    4371b0f0a3e2478ca1d8123525e8eef1:
      title: The Secret Vajra Knot
      parent: Secret Vajra Knot
    f082867e71bb44058fd7e8d323395981:
      title: Prayer for the Long Life of His Holiness the Dalai Lama
      parent: Long Life Prayers
    a42671c2613f4cce89c7f42d478be7ef:
      title: 'The Music of Immortality: A Prayer for the Long Life of His Holiness
        the Dalai Lama'
      parent: Long Life Prayers
    7cd339b894d745b8ab1028d8b876d22b:
      title: General Long-Life Prayer
      parent: Long Life Prayers
    f8725f659eea4d4e8b54932d5d96efd4:
      title: 'The Melodious Song of Immortality: A Prayer for Long Life'
      parent: Long Life Prayers
    6b03ea48a9d44cb59dd7583d452916a3:
      title: 'Words to Delight the Sovereigns of the Dharma: A Prayer of Aspiration
        for the Flourishing and Spread of the Ancient Translation Tradition'
      parent: Prayer for Spread of Nyingma Tradition
    87a89b9d248c4e04a3e00680c9938347:
      title: 'Final Words: The Essential Advice'
      parent: Final Words
created_at: '2022-03-01T04:58:17.003885'
last_modified_at: '2022-03-01T04:58:17.003888'
statistics:
  total_words: 41410
  total_non_words: 3485
quality:
  non_words_ratio: 0.08
